import { Module } from '@nestjs/common';
import { GraphQLModule } from '@nestjs/graphql';
import { TypeOrmModule, TypeOrmModuleOptions } from '@nestjs/typeorm';
import { EmployeeModule } from './employee/EmployeeModule';
import { ApolloDriver } from '@nestjs/apollo';
import { ConfigModule } from '@app/config/ConfigModule';
import { ConfigContainer } from '@app/config/config/ConfigContainer';

@Module({
  imports: [
    ConfigModule.forRoot(),
    GraphQLModule.forRoot({
      driver: ApolloDriver,
      autoSchemaFile: 'autogenerated/schema.gql',
    }),
    TypeOrmModule.forRootAsync({
      useFactory: (config: ConfigContainer): TypeOrmModuleOptions =>
        config.database,
      inject: [ConfigContainer],
    }),
    EmployeeModule,
  ],
})
export class AppModule {}
